version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ihab2003*
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      PYTHONPATH: /app
    volumes:
      - .:/app
    depends_on:
      - mysql

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-container
    depends_on:
      - mysql
    environment:
      FLASK_ENV: testing
      PYTHONPATH: /app
    volumes:
      - .:/app
    entrypoint: ["pytest", "-v", "--maxfail=1", "--disable-warnings"]

  customers:
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    container_name: customers-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - mysql

  inventory:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    container_name: inventory-service
    restart: always
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - mysql
      
volumes:
  mysql_data:
