version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ihab2003*
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql

volumes:
  mysql_data:
