version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: N4j1n4j1
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-container
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      PYTHONPATH: /app:/app/../
    volumes:
      - .:/app
      - ./database:/app/../database
    depends_on:
      - mysql

  customers:
    build:
      context: ./services/customers
      dockerfile: Dockerfile
    container_name: customers-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - ./services/customers:/app
      - ./database:/app/../database  
    depends_on:
      - mysql

  inventory:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    container_name: inventory-service
    restart: always
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - ./services/inventory:/app
    depends_on:
      - mysql

  review:
    build:
      context: ./services/review
      dockerfile: Dockerfile
    container_name: review-service
    restart: always
    ports:
      - "5003:5003"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - ./services/review:/app
    depends_on:
      - mysql

  sales:
    build:
      context: ./services/sales
      dockerfile: Dockerfile
    container_name: sales-service
    restart: always
    ports:
      - "5004:5004"
    environment:
      FLASK_APP: routes.py
      FLASK_ENV: development
    volumes:
      - ./services/sales:/app
    depends_on:
      - mysql

volumes:
  mysql_data:
